[tool.poetry]
name = "sandbox"
version = "0.1.0"
description = ""
authors = ["Hibiki"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.2"
psycopg2 = "2.9.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
